### ISSUE TITLE
CoreMods supports more target types after forge 1.14.3-27.0.16 

### ISSUE THREAD

**Issue by ZekerZhayard** [xfl03/CoreModTutor#3]
CoreMods [0.6.2](https://github.com/MinecraftForge/CoreMods/commit/fd217c89781d16e8a9aef5d19aa469bc4eb4f685) 开始支持新的 target type.
```JavaScript
function initializeCoreMod() {
    return {
        "MethodTransformer": {
            "target": {
                "type": "METHOD",
                "class": "net.minecraft.client.Minecraft",
                "methodName": "func_1234_a",
                "methodDesc": "(Ljava/lang/String;)Z"
            },
            "transformer": function (method) {
                return method
            }
        },
        "FieldTransformer": {
            "target": {
                "type": "FIELD",
                "class": "net.minecraft.client.Minecraft",
                "fieldName": "field_5678_b"
            },
            "transformer": function (field) {
                return field
            }
        }
    }
}
```

**Comment by xfl03** [comment]
这几天打算更新一下1.14相关的内容，不少东西改了

**Comment by ZekerZhayard** [comment]
刚刚推的 forge-1.14.4-28.0.45 所使用的 ModLauncher 3.2.0 貌似能正确地支持普通模组使用 `ITransformationService` 了

**Comment by xfl03** [comment]
已更新1.14.4的相关内容，请多提宝贵意见！
https://xfl03.gitbook.io/coremodtutor/

**Comment by ZekerZhayard** [comment]
在`ITransformationService`里还有两个比较重要的方法
- `additionalClassesLocator`: 应该是用于定位CoreMod加载阶段需要的类的位置，因为一方面ModLauncher不再把反混淆后的Minecraft本体和所有模组加进classpath里，而是直接用URL定位，（~~这也就是为什么能不做任何操作，直接在模组中使用核心文件替换法的原因吧~~）另一方面也为了避免模组在这个阶段使用Minecraft本身的类。如果所有实现`ITransformationService`的类的`additionalClassesLocator`都没有定位到引用的类，那么就会抛出`ClassNotFoundException`。
- `additionalResourcesLocator`: 应该是用于定位资源文件的位置，比如用`xxx.class.getResource("xxx")`的形式访问资源文件的时候会调用这个方法。

**Comment by xfl03** [comment]
classpath本身就是url的集合，ModLauncher不再使用URLClassLoader来进行类加载了，自己完成了Minecraft及Mod相关类的url管理，优先从libraries和Mod中加载类，因此才可以直接核心文件替换。
对于那两个方法我的理解是允许CoreMod增加类的URL和资源的URL，而不是限制CoreMod阶段可以使用的类。

* `arguments`，接收一个处理游戏参数的双重映射函数，可以在这里添加自己的参数
* `argumentValues`，接收游戏参数，可以在这里获得游戏参数
* `additionalClassesLocator`，返回一个包名前缀和用于寻找类的类名映射URL函数的组合，可以通过这个方法可以往ClassLoader中增加自定义的用于类加载的URL
* `additionalClassesLocator`，返回一个文件路径和用于寻找文件的文件名映射URL函数的组合，可以通过这个方法可以往ClassLoader中增加自定义的用于类以外的资源加载的URL

**Comment by ZekerZhayard** [comment]
**之前我记错了，我只记得forge-1.14.4-28.0.45刚出来的时候，踩了一个坑，刚刚才想起来：**
ExampleTransformationService.java
```java
package com.example;

import java.util.Collections;
import java.util.List;
import java.util.Set;
import javax.annotation.Nonnull;

import cpw.mods.modlauncher.api.IEnvironment;
import cpw.mods.modlauncher.api.ITransformationService;
import cpw.mods.modlauncher.api.ITransformer;
import cpw.mods.modlauncher.api.IncompatibleEnvironmentException;

public class ExampleTransformationService implements ITransformationService {
    @Nonnull @Override public String name() { return "example"; }
    @Override public void initialize(IEnvironment environment) { }
    @Override public void beginScanning(IEnvironment environment) { }
    @Override public void onLoad(IEnvironment env, Set<String> otherServices) throws IncompatibleEnvironmentException { }
    @Nonnull @Override public List<ITransformer> transformers() { return Collections.singletonList(new ExampleTransformer()); }
}
```

ExampleTransformer.java
```java
package com.example;

import java.util.Collections;
import java.util.Set;
import javax.annotation.Nonnull;

import cpw.mods.modlauncher.api.ITransformer;
import cpw.mods.modlauncher.api.ITransformerVotingContext;
import cpw.mods.modlauncher.api.TransformerVoteResult;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;

public class ExampleTransformer implements ITransformer<MethodNode> {
    @Nonnull @Override public MethodNode transform(MethodNode input, ITransformerVotingContext context) {
        input.instructions.insert(new MethodInsnNode(Opcodes.INVOKESTATIC, "com/example/ExampleClass", "test", "()V", false));
        return input;
    }

    @Nonnull @Override public TransformerVoteResult castVote(ITransformerVotingContext context) {
        return TransformerVoteResult.YES;
    }

    @Nonnull @Override public Set<Target> targets() {
        return Collections.singleton(Target.targetMethod("net.minecraft.client.main.Main", "main", "([Ljava/lang/String;)V"));
    }
}
```

ExampleClass.java
```java
package com.example;

public class ExampleClass {
    public static void test() {
        System.out.println("1111");
    }
}
```

**上面这段代码运行之后会抛异常：**
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 4 more
Caused by: java.lang.NoClassDefFoundError: com/example/ExampleClass
	at net.minecraft.client.main.Main.main(SourceFile)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.example.ExampleClass
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

**这个时候需要重写`additionalClassesLocator`来确定`ExampleClass`的位置**

~~这个`additionalClassesLocator`的想法似乎是sp614x提出的？~~

**Comment by xfl03** [comment]
我的理解是这样的，为了防止CoreMod胡乱加载类，CoreMod操作的classloader和游戏的classloader并不一致，所以需要coremod手动将自己加入后者的classloader中以便后续使用。
确实是sp614x提出的：https://github.com/cpw/modlauncher/issues/31
对于ModDirTransformerDiscoverer的理解，这个应该是用来加载TransformationService的，并将他们排除出普通mod的列表，同时加入[特殊classloader](https://github.com/cpw/modlauncher/blob/master/src/main/java/cpw/mods/modlauncher/TransformationServicesHandler.java#L153)用以实现隔离的功能。

**Comment by ZekerZhayard** [comment]
这样就能最大限度地避免CoreMod使用不该使用的类，

> |项目|Java|JavaScript|
> |--|--|--|
> |操作风险|需要开发者特别注意不能在CoreMod阶段调用任何原版类和其他Mod，提前加载这些类会导致错误|不会导致类提前加载|

我觉得这一条可能需要修改一下，因为无论使用Java还是JavaScript，调用原版类都会受限，只不过使用Java在开发环境下能成功调用原版类，但是是由不同类加载器加载的，在生产环境下调用直接抛ClassNotFoundException，但无论在开发环境还是生产环境下，都不会影响后续的字节码修改，这一点是原先LaunchWrapper做不到的。
看LexManos的意思应该是希望模组把CoreMod部分和普通Mod部分分成两个jar包，所以后续会有additionalClassesLocator的设计
